Setup Sphinx documentation (#211)
This PR starts to setup the Sphinx documentation. 

A few things are still missing and will need to be addressed:
- [x] Better looking documentation. For the moment only the API
documentation, automatically generated from docstrings, is available. It
would be better to
  - [x] Write down some glue text to introduce the package,
  - [x] Fix some of the formatting issues (e.g., long function names).
- [x] Fix the different warnings / errors produced when running `make
html`:
  ```
/workspaces/tqec/src/tqec/circuit/operations/operation.py:docstring of
tqec.circuit.operations.operation.RelativeMeasurementData.relative_measurement_offset:1:
WARNING: duplicate object description of
tqec.circuit.operations.operation.RelativeMeasurementData.relative_measurement_offset,
other instance in source/tqec.circuit.operations, use :no-index: for one
of them
/workspaces/tqec/src/tqec/circuit/operations/operation.py:docstring of
tqec.circuit.operations.operation.RelativeMeasurementData.relative_qubit_positioning:1:
WARNING: duplicate object description of
tqec.circuit.operations.operation.RelativeMeasurementData.relative_qubit_positioning,
other instance in source/tqec.circuit.operations, use :no-index: for one
of them
/workspaces/tqec/src/tqec/circuit/operations/transformer.py:docstring of
tqec.circuit.operations.transformer.transform_to_stimcirq_compatible:11:
WARNING: Bullet list ends without a blank line; unexpected unindent.
/workspaces/tqec/src/tqec/templates/base.py:docstring of
tqec.templates.base.Template.scale_to:10: ERROR: Unexpected indentation.
/workspaces/tqec/src/tqec/templates/base.py:docstring of
tqec.templates.base.Template.scale_to:11: WARNING: Block quote ends
without a blank line; unexpected unindent.
/workspaces/tqec/src/tqec/templates/shifted.py:docstring of
tqec.templates.shifted.ShiftedTemplate.scale_to:10: ERROR: Unexpected
indentation.
/workspaces/tqec/src/tqec/templates/shifted.py:docstring of
tqec.templates.shifted.ShiftedTemplate.scale_to:11: WARNING: Block quote
ends without a blank line; unexpected unindent.
/workspaces/tqec/src/tqec/templates/stack.py:docstring of
tqec.templates.stack.StackedTemplate.scale_to:10: ERROR: Unexpected
indentation.
/workspaces/tqec/src/tqec/templates/stack.py:docstring of
tqec.templates.stack.StackedTemplate.scale_to:11: WARNING: Block quote
ends without a blank line; unexpected unindent.
/workspaces/tqec/src/tqec/templates/atomic/rectangle.py:docstring of
tqec.templates.atomic.rectangle.AlternatingRectangleTemplate.scale_to:10:
ERROR: Unexpected indentation.
/workspaces/tqec/src/tqec/templates/atomic/rectangle.py:docstring of
tqec.templates.atomic.rectangle.AlternatingRectangleTemplate.scale_to:11:
WARNING: Block quote ends without a blank line; unexpected unindent.
/workspaces/tqec/src/tqec/templates/atomic/rectangle.py:docstring of
tqec.templates.atomic.rectangle.RawRectangleTemplate.scale_to:10: ERROR:
Unexpected indentation.
/workspaces/tqec/src/tqec/templates/atomic/rectangle.py:docstring of
tqec.templates.atomic.rectangle.RawRectangleTemplate.scale_to:11:
WARNING: Block quote ends without a blank line; unexpected unindent.
/workspaces/tqec/src/tqec/templates/atomic/square.py:docstring of
tqec.templates.atomic.square.AlternatingCornerSquareTemplate.scale_to:10:
ERROR: Unexpected indentation.
/workspaces/tqec/src/tqec/templates/atomic/square.py:docstring of
tqec.templates.atomic.square.AlternatingCornerSquareTemplate.scale_to:11:
WARNING: Block quote ends without a blank line; unexpected unindent.
  ```

---------

Co-authored-by: Sam Burdick <samuelmburdick@gmail.com>